### ISSUE TITLE
Broken front page links

### ISSUE THREAD

**Issue by qbatten** [phillycommunitywireless/docs#16]
The "Hardware" and "Installations" links go to https://docs.phillycommunitywireless.org/en/latest/hardware/, but that 404s. I think the right page is https://docs.phillycommunitywireless.org/en/latest/installations/hardware/ (that's where the sidebar link for "Hardware" takes you).

<img width="496" alt="image" src="https://user-images.githubusercontent.com/9345870/185762158-4b2ed219-502d-408f-9e04-8880458e60ec.png">

**Comment by qbatten** [comment]
I have a (small) pr that fixes this, can I be added as a contributor plz?

**Comment by hawc2** [comment]
thanks @qbatten, you're added!
