### ISSUE TITLE
Hardware list has character encoding issues

### ISSUE THREAD

**Issue by HotelCalifornia** [phillycommunitywireless/docs#6]
this line (and subsequent lines)

https://github.com/phillycommunitywireless/docs/blob/e64fa3c23bfccc18c4c36bc61f62bc2746fd692d/docs/hardware.md?plain=1#L54

use/s `U+201D RIGHT DOUBLE QUOTATION MARK` which doesn't get translated into the proper HTML entity `&rdquo;` when the site is generated:

<img width="707" alt="screenshot of docs.phillycommunitywireless.com/en/latest/hardware showing malformed characters" src="https://user-images.githubusercontent.com/6646541/168502063-706911b9-ae37-48de-97ce-8cc4b55e7bfc.png">

**Comment by hawc2** [comment]
Thanks Alex! Good catch - I think it's all fixed now
