### ISSUE TITLE
ssh into mesh ap post-adoption

### ISSUE THREAD

**Issue by hawc2** [phillycommunitywireless/docs#9]
ran into an issue trying to ssh into a mesh ap device after it's been adopted. the username password prompt is confusing, only asks for a password (not username), and i can't log in with the credentials on Hostifi as described in this article: https://controllific.com/how-to-ssh-into-unifi-ap/

**Comment by dzygmundfelt** [comment]
@hawc2 the ssh command is something like 
```
ssh username@ip.add.ress
```
The example in the link you sent has `admin` as the username, so I'm wondering if you're using `admin` as the username in your ssh command, instead of the username that's in the credentials on Hostifi.

**Comment by hawc2** [comment]
@dzygmundfelt  that makes sense. I tried it with a device that was still online in Hostifi, and it didn't seem to work. Do you think the device has to be first forgotten on Hostifi to be able to SSH into it? Or that it can't be in the presence of the PCW network because then it will sync and block SSHing? Or maybe there's another reason it's not working. . . 

I figured out some other minor steps in the process and updated the docs. Definitely need a static IP to connect to the APs, although I haven't found that well documented.

**Comment by dzygmundfelt** [comment]
We discussed this ticket in last week's meeting, and it sounds like this is kind of difficult problem to solve. I'm gonna move it out of `To do` for now.

**Comment by hawc2** [comment]
@allanxgomez has figured this one out, including through UISP to connect to Unifi APs. it does work with the admin username/pword as described
